
package Formularios;

import Clases.*;
import DAO.*;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import java.text.ParseException;
import java.text.SimpleDateFormat;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class dlgEliminarVentaDetalle extends javax.swing.JDialog {
    
    // VAriables
    DefaultTableModel tbmVentas;
    DAOVenta venta_dao = new DAOVenta();
    DAOVentaDetalle ventaDetalle_dao = new DAOVentaDetalle();
    DAOServicio servicio_dao = new DAOServicio();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgEliminarVentaDetalle.class.getName());

    /**
     * Creates new form dlgEliminarVentaDetalle
     */
    public dlgEliminarVentaDetalle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarVentasDetalle();
        cargarVentas();
    }
    
    public void cargarVentasDetalle(){
                
        List<CVentaDetalle> listaVentasDetalle = ventaDetalle_dao.listaVentasDetalle();
        tbmVentas = (DefaultTableModel)tabVenta.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listaVentasDetalle.size(); i++) {
            CVentaDetalle detalle = listaVentasDetalle.get(i);
            CServicio servicio = detalle.getServicio();

            // ✅ Construimos el texto completo del servicio
            String descripcionServicio = servicio.getNombre();

            if (servicio.getMarca() != null) {
                String marca = servicio.getMarca().getMarca();
                String modelo = servicio.getMarca().getModelo();
                int año = servicio.getMarca().getAño();
                descripcionServicio += " " + marca + " " + modelo + " " + año;
            }
        
            ob[0] = detalle.getId();
            ob[1] = detalle.getVenta().getId();
            ob[2] = descripcionServicio; // ✅ Texto completo
            ob[3] = detalle.getCantidad();
            ob[4] = detalle.getPrecio_unit();
            ob[5] = detalle.getSubtotal();
            tbmVentas.addRow(ob);
        }        
        tabVenta.setModel(tbmVentas);
    }
    
    public void cargarVentas(){
                
        List<CVenta> listaVentas = venta_dao.listaVentas();
        for (int i = 0; i < listaVentas.size(); i++) {
            Integer cod = listaVentas.get(i).getId();
            //Integer cod = listaVentas.get(i).getId();
            cbxVenta.addItem(cod.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxVenta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVenta = new javax.swing.JTable();
        txtSubtotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Registro de Venta");

        cbxVenta.setEnabled(false);
        cbxVenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxVentaItemStateChanged(evt);
            }
        });
        cbxVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVentaActionPerformed(evt);
            }
        });

        tabVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "VENTA", "SERVICIO", "CANTIDAD", "PRECIO UNITARIO", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabVenta);

        txtSubtotal.setEditable(false);
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Subtotal:");

        txtId.setEditable(false);
        txtId.setToolTipText("");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        jLabel5.setText("Id:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(cbxVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxVentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxVentaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVentaItemStateChanged

    private void cbxVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxVentaActionPerformed

    private void tabVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVentaMouseClicked
        // TODO add your handling code here:
        Integer k = tabVenta.getSelectedRow();

        txtId.setText(tabVenta.getValueAt(k, 0).toString());
        cbxVenta.setSelectedItem(tabVenta.getValueAt(k, 1).toString());
        txtSubtotal.setText(tabVenta.getValueAt(k, 5).toString());
    }//GEN-LAST:event_tabVentaMouseClicked

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        // Dialogo de confirmación
        int opcion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro de eliminar registro de venta "+txtId.getText()+"?" ,
            "Eliminar Registro",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION)
        {
            if (txtId.getText().length()>0){
                int id = Integer.parseInt(txtId.getText());
                CVentaDetalle previaVentaDetalle = ventaDetalle_dao.obtenerVentaDetalle(id);
                double subtotalAnterior = previaVentaDetalle.getSubtotal()*-1;
                System.out.println(subtotalAnterior);
                int id_venta = Integer.parseInt(cbxVenta.getSelectedItem().toString());
                boolean pre_actualizado= venta_dao.actualizarTotalVenta(id_venta, subtotalAnterior);
                System.out.println(pre_actualizado);
                if (ventaDetalle_dao.eliminarVentaDetalle(id)){
                    JOptionPane.showMessageDialog(this, "Registro eliminado");
                    txtId.setText("");
                    txtSubtotal.setText("");
                    for (int i = tbmVentas.getRowCount()-1; i >=0; i--) {
                        tbmVentas.removeRow(i);
                    }
                    cargarVentasDetalle();
                }else
                JOptionPane.showMessageDialog(this, "Error");
            }else
            JOptionPane.showMessageDialog(this, "Seleccione una marca");
        }else
        this.dispose();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgEliminarVentaDetalle dialog = new dlgEliminarVentaDetalle(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cbxVenta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabVenta;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
