
package Formularios;

import Clases.*;
import DAO.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class dlgModificarServicio extends javax.swing.JDialog {
    
    // Variables
    DAOServicio servicio_dao = new DAOServicio();
    DAOMarca marca_dao = new DAOMarca();
    DefaultTableModel tbmProductos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgModificarServicio.class.getName());

    /**
     * Creates new form dlgModificarServicio
     */
    public dlgModificarServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //
        cargarProductos();
        cargarMarcas();
    }
    
    public void cargarProductos(){
                
        List<CServicio> listaServicios = servicio_dao.listaServicios();
        tbmProductos = (DefaultTableModel)tabServicio.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < listaServicios.size(); i++) {
            ob[0] = listaServicios.get(i).getId();
            ob[1] = listaServicios.get(i).getNombre();
            ob[2] = listaServicios.get(i).getMarca().getMarca();
            ob[3] = listaServicios.get(i).getPrecio();
            ob[4] = listaServicios.get(i).getStock();
            ob[5] = listaServicios.get(i).isActivo();
            tbmProductos.addRow(ob);
        }        
        tabServicio.setModel(tbmProductos);
    }
    
    public void cargarMarcas(){
                
        List<CMarca> listaMarcas = marca_dao.listaMarcas();
        for (int i = 0; i < listaMarcas.size(); i++) {
            cbxMarca.addItem(listaMarcas.get(i).getMarca());
            Integer cod = listaMarcas.get(i).getId();
            cbxCodigoMarca.addItem(cod.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spStock = new javax.swing.JSpinner();
        chkboxActivo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabServicio = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        txtServicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxMarca = new javax.swing.JComboBox<>();
        cbxCodigoMarca = new javax.swing.JComboBox<>();
        spPrecio = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Servicio");

        chkboxActivo.setText("Activo");
        chkboxActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxActivoActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tabServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVICIO", "MARCA", "PRECIO", "STOCK", "ACTIVO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabServicio);

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Servicio:");

        cbxMarca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMarcaItemStateChanged(evt);
            }
        });

        cbxCodigoMarca.setEnabled(false);

        spPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        jLabel2.setText("Precio:");

        jLabel3.setText("Stock");

        jLabel5.setText("Id:");

        txtId.setEditable(false);
        txtId.setToolTipText("");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spStock)
                                        .addGap(44, 44, 44)
                                        .addComponent(chkboxActivo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(cbxCodigoMarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnModificar)))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCodigoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkboxActivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkboxActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxActivoActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        if (txtId.getText().length()>0){
            Integer id = Integer.parseInt(txtId.getText());
            String nombre = txtServicio.getText();
            double precio = Double.parseDouble(spPrecio.getValue().toString());
            int stock = Integer.parseInt(spStock.getValue().toString());
            boolean activo = chkboxActivo.isSelected();
            int id_marca = Integer.parseInt(cbxCodigoMarca.getSelectedItem().toString());

            if ((nombre.length()>0) && (precio>0)&& (stock>0)){
                if (servicio_dao.modificarServicio(new CServicio(id, nombre,new CMarca(id_marca,"","",0,0), precio, stock, activo
                ))){
                    JOptionPane.showMessageDialog(this, "Servicio modificado");
                    //
                    txtId.setText("");
                    txtServicio.setText("");
                    txtServicio.requestFocus();
                    spPrecio.setValue(0);
                    spStock.setValue(0);
                    chkboxActivo.setSelected(false);
                    //
                    cbxMarca.setSelectedIndex(0);
                    cbxCodigoMarca.setSelectedIndex(0);
                    //
                    for (int i = tbmProductos.getRowCount()-1; i >=0; i--) {
                        tbmProductos.removeRow(i);
                    }
                    cargarProductos();
                }
                else
                JOptionPane.showMessageDialog(this, "Error");
            }
            else
            JOptionPane.showMessageDialog(this, "Los campos deben ser válidos");
        } else
        JOptionPane.showMessageDialog(this, "Seleccione un servicio");
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void cbxMarcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMarcaItemStateChanged
        // TODO add your handling code here:
        int k = cbxMarca.getSelectedIndex();
        if(cbxCodigoMarca.getItemCount()>0)
        cbxCodigoMarca.setSelectedIndex(k);
    }//GEN-LAST:event_cbxMarcaItemStateChanged

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void tabServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabServicioMouseClicked
        // TODO add your handling code here:
        Integer k = tabServicio.getSelectedRow();

        txtId.setText(tabServicio.getValueAt(k, 0).toString());
        txtServicio.setText(tabServicio.getValueAt(k, 1).toString());
        cbxMarca.setSelectedItem(tabServicio.getValueAt(k, 2).toString());
        spPrecio.setValue(tabServicio.getValueAt(k, 3));
        spStock.setValue(tabServicio.getValueAt(k, 4));
        chkboxActivo.setSelected((Boolean) tabServicio.getValueAt(k, 5));
    }//GEN-LAST:event_tabServicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgModificarServicio dialog = new dlgModificarServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxCodigoMarca;
    private javax.swing.JComboBox<String> cbxMarca;
    private javax.swing.JCheckBox chkboxActivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spPrecio;
    private javax.swing.JSpinner spStock;
    private javax.swing.JTable tabServicio;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtServicio;
    // End of variables declaration//GEN-END:variables
}
