
package Formularios;

import Clases.*;
import DAO.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class dlgModificarVenta extends javax.swing.JDialog {
    
    // Variables
    DAOVenta venta_dao = new DAOVenta();
    DAOCliente cliente_dao = new DAOCliente();
    DefaultTableModel tbmProductos;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dlgModificarVenta.class.getName());

    /**
     * Creates new form dlgModificarVenta
     */
    public dlgModificarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Obtebner la fecha actual
        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(formatoFecha.format(new Date()));
        
        cargarVentas();
        cargarClientes();
    }
    
    public void cargarVentas(){
                
        List<CVenta> listaVentas = venta_dao.listaVentas();
        tbmProductos = (DefaultTableModel)tabServicio.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < listaVentas.size(); i++) {
            ob[0] = listaVentas.get(i).getId();
            ob[1] = listaVentas.get(i).getFecha();
            ob[2] = listaVentas.get(i).getCliente().getNombres();
            ob[3] = listaVentas.get(i).getTotal();
            tbmProductos.addRow(ob);
        }        
        tabServicio.setModel(tbmProductos);
    }
    
    public void cargarClientes(){
                
        List<CCliente> listaClientes = cliente_dao.listaClientes();
        for (int i = 0; i < listaClientes.size(); i++) {
            cbxCliente.addItem(listaClientes.get(i).getNombres());
            Integer cod = listaClientes.get(i).getId();
            cbxCodigoCliente.addItem(cod.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabServicio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cbxCliente = new javax.swing.JComboBox<>();
        cbxCodigoCliente = new javax.swing.JComboBox<>();
        spTotal = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "CLIENTE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabServicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabServicio);

        jLabel1.setText("Fecha:");

        cbxCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxClienteItemStateChanged(evt);
            }
        });

        cbxCodigoCliente.setEnabled(false);

        spTotal.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 0.1d));

        jLabel2.setText("Total:");

        jLabel5.setText("Id:");

        txtId.setEditable(false);
        txtId.setToolTipText("");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar)
                        .addGap(77, 77, 77))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnModificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxClienteItemStateChanged
        // TODO add your handling code here:
        int k = cbxCliente.getSelectedIndex();
        if(cbxCodigoCliente.getItemCount()>0)
        cbxCodigoCliente.setSelectedIndex(k);
    }//GEN-LAST:event_cbxClienteItemStateChanged

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        // TODO add your handling code here:
        if (txtId.getText().length()>0){
            Integer id = Integer.parseInt(txtId.getText());
            String fecha = txtFecha.getText();
            double total = Double.parseDouble(spTotal.getValue().toString());
            System.out.println(total);
            int id_cliente = Integer.parseInt(cbxCodigoCliente.getSelectedItem().toString());

            if ((fecha.length()>0) && (total>0)){
                try {
                // 1. Convertir el String "dd/MM/yyyy" a java.util.Date
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date fechaUtil = formato.parse(fecha);

                // 2. Convertir java.util.Date a java.sql.Date
                //java.sql.Date fechaSql = new java.sql.Date(fechaUtil.getTime());

                // 3. Crear el objeto CVenta con el java.sql.Date
                CVenta nuevaVenta = new CVenta(id, fechaUtil, new CCliente(id_cliente, "", "", "", "", ""), total);

                // 4. Llamar al DAO con el objeto CVenta ya procesado
                    if (venta_dao.modificarVenta(nuevaVenta)){
                        JOptionPane.showMessageDialog(this, "Venta modificada");
                        //
                        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                        txtFecha.setText(formatoFecha.format(new Date()));
                        txtFecha.requestFocus();
                        spTotal.setValue(0);
                        //
                        cbxCliente.setSelectedIndex(0);
                        cbxCodigoCliente.setSelectedIndex(0);
                        //
                        for (int i = tbmProductos.getRowCount()-1; i >=0; i--) {
                            tbmProductos.removeRow(i);
                        }
                        cargarVentas();
                    }
                    else
                    JOptionPane.showMessageDialog(this, "Error");
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(this, "El formato de la fecha es inválido. Use dd/mm/yyyy.");
                    System.err.println("Error de parseo de fecha: " + e.getMessage());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado.");
                    System.err.println("Error: " + e.getMessage());
                }
            }
            else
            JOptionPane.showMessageDialog(this, "Los campos deben ser válidos");
        } else
        JOptionPane.showMessageDialog(this, "Seleccione un servicio");
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tabServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabServicioMouseClicked
        // TODO add your handling code here:
        Integer k = tabServicio.getSelectedRow();

        txtId.setText(tabServicio.getValueAt(k, 0).toString());
        DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        //txtFecha.setText(formatoFecha.format(new Date()));
        txtFecha.setText(formatoFecha.format(tabServicio.getValueAt(k, 1)));
        cbxCliente.setSelectedItem(tabServicio.getValueAt(k, 2).toString());
        spTotal.setValue(tabServicio.getValueAt(k, 3));
    }//GEN-LAST:event_tabServicioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                dlgModificarVenta dialog = new dlgModificarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxCodigoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spTotal;
    private javax.swing.JTable tabServicio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
